a=int(input('a='))
b=int(input('b='))
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a**b)
print(a%b)
if a>b:
    print('a lon hon b')
elif a<b:
    print('a nho hon b')
else:
    print('a bang b')
print(a&b)
print(a|b)
print(a^b)
print(not(a==b))
print(a/10)
print(a*10)